### ISSUE TITLE
Underclocked consumption is even better than you've mentioned

### ISSUE THREAD

**Issue by serjepatoff** [nhasbun/pico_power_saving#1]
My amperemeter shows even better result: 4.5 mA minimum underclocked current consumption instead of 5.5 mA when connecting +5V to VSYS instead of VBUS (so that Shottky diode dropout is evaded).

PS. Thank you for great example.

**Comment by serjepatoff** [comment]
Of course it might be a matter of either amperemeter precision, or pi pico manufacturing parameters variation, but sub-5mA consumption was very important for my circuit.

**Comment by nhasbun** [comment]
My current measurement circuit lacked precision, so my numbers should be taken with a grain of salt. You have a very interesting point that I overlooked about the Schottky diode, though.

It would be awesome if you could spare a few minutes and update the repo readme with your notes about the power consumption gains when using VSYS vs VBUS. It would make a great addition to anyone looking for help regarding power saving on the pico board.
